### ISSUE TITLE
Remove yellow outline

### ISSUE THREAD

**Issue by AndaHendriksen** [isaacHagoel/solid-dnd-directive#12]
How do I remove the yellow outline on the section when dragging?

**Comment by isaacHagoel** [comment]
you can use the "dropTargetStyle" option (see README)

**Comment by AndaHendriksen** [comment]
@isaacHagoel damn, don't know how I missed that! Thanks

**Comment by isaacHagoel** [comment]
No worries:)
Closing the issue. Let me know if you need anything else
