### ISSUE TITLE
Question: Nesting DND

### ISSUE THREAD

**Issue by davedbase** [isaacHagoel/solid-dnd-directive#4]
@isaacHagoel this utility is fantastic. I've been able to use it successfully in a project that requires extremely complex DND functionality. Here's an example of my current prototype: https://radius-stage.pilotio.workers.dev/

The next battle I'm facing is making the cards sortable within nested cards. Imagine if I could "expand" a card which reveals a drop area allowing me to move cards from anywhere into it.

Do you have any suggestions on how to solve this? I'd appreciate the pointers!

**Comment by isaacHagoel** [comment]
so u basically need another level of nesting?
what can go inside from where (as in does it have a different "type")
maybe if you draw something on paper and attach it would be easier for me to understand what you're after

**Comment by davedbase** [comment]
Yup, here's a mockup of what I'm looking to achieve.

<img width="600" alt="Screen Shot 2021-10-19 at 8 58 11 AM" src="https://user-images.githubusercontent.com/1168397/137914129-9e8f10e3-217b-4f90-b483-536ef39d5c0d.png">

Each of the rows here are draggable but notice how the lists for each are expandable by pool? Theoretically this can be an n deep nesting structure. You should be able to drill as deep down as you'd like and move between any of the questions.

Beyond that the other issue to solve is how can I move multiple items at once? Haha.

Lots going on in our UI, hehe

**Comment by isaacHagoel** [comment]
Sorry, I haven't had a chance to look yet. hopefully over the weekend.
nesting is supported by the core lib and it would be a matter of
understanding how to use it within Solid.
Dragging multiple elements is not supported at the moment though.

**Comment by davedbase** [comment]
No worries, we all get busy =) when you have a chance your input/advice is definitely appreciated.

From what I can tell I don't see anything that would disallow this nesting. In regards to multiple dragging, is this something you'd be open to adding? It's rather useful to our UI and I could likely even contribute a donation for your time.

**Comment by isaacHagoel** [comment]
Hi, have you tried nesting zones. it should be straightforward (unless the zones are recursive and then there is one small gotcha to beware of)??
regarding multi-dragging, I looked into the code a bit. I think adding these features will take a few full days of work.
I don't know how I feel about a donation but if you can allocate a developer to work on it for say a week, I can guide and supports them with no charge.

**Comment by davedbase** [comment]
Yeah they will likely be recursive because we'll support deep nesting. What do you suggest the gotcha will be for me to be aware of?

Hmmm, a week of developer effort would be a bit more effort than we can take away from our dev cycle. No worries though I thought supporting the evolution of the project might bring a general benefit and get a donation in your pocket. Would save us on the dev effort we can eat right now.

**Comment by isaacHagoel** [comment]
This is how it is done in Svelte with the core lib:
https://svelte.dev/repl/fe8c9eca04f9417a94a8b6041df77139?version=3.35.0

For the gotcha see line 32 in Content.svelte
I haven't create the Solid version of this yet but I don't think it should take more than an hour.
If you do it send me a link and I will add to the list of examples.
About the multidrag, do u have a specific implementation in mind?

**Comment by davedbase** [comment]
Ah, awesome I'm not a Svelte user so the syntax is lost on my but I generally get the idea. The gotcha is a bit trickier for me to see. If you do get a chance to implement, let me know. I can hack my way through it but seeing how you'd solve it properly would be helpful.

**Comment by isaacHagoel** [comment]
Hi, I made an example for multi drag in the svelte implantation (should be transferrable to Solid). Just FYI
https://svelte.dev/repl/c4eb917bb8df42c4b17402a7dda54856?version=3.24.1
