### ISSUE TITLE
dndzone is not defined

### ISSUE THREAD

**Issue by targetlucked69** [isaacHagoel/solid-dnd-directive#6]
Hi, tried this directive on a fresh solid + vite app

1. `npx degit solidjs/templates/ts solid-dnd-test`
2. `npm install && npm install solid-dnd-directive`
3. Add demo code

```tsx
import { createSignal, For } from "solid-js";
import { dndzone } from "solid-dnd-directive";
const containerStyle = {
  border: "1px solid black",
  padding: "0.3em",
  "max-width": "200px",
};
const itemStyle = {
  border: "1px solid blue",
  padding: "0.3em",
  margin: "0.2em 0",
};

function App() {
  const [items, setItems] = createSignal([
    { id: 1, title: "item 1" },
    { id: 2, title: "item 2" },
    { id: 3, title: "item 3" },
  ]);

  function handleDndEvent(e) {
    const { items: newItems } = e.detail;
    setItems(newItems);
  }
  return (
    <main>
      <section
        style={containerStyle}
        use:dndzone={{ items }}
        on:consider={handleDndEvent}
        on:finalize={handleDndEvent}
      >
        <For each={items()}>
          {(item) => <div style={itemStyle}>{item.title}</div>}
        </For>
      </section>
    </main>
  );
}

export default App;
```

Error:
<img width="495" alt="Screen Shot 2022-02-10 at 12 07 35 PM" src="https://user-images.githubusercontent.com/72330740/153335275-57be09cc-0657-4e17-84cb-1c18b2bd7013.png">

<img width="779" alt="Screen Shot 2022-02-10 at 12 07 54 PM" src="https://user-images.githubusercontent.com/72330740/153335300-9977d070-9b22-4de6-a066-795f482b745c.png">

**Comment by isaacHagoel** [comment]
is it a typescript error?
does it work without typescript?

**Comment by targetlucked69** [comment]
It works without TypeScript.

**Comment by isaacHagoel** [comment]
so i think u just need to declare it.
see https://www.solidjs.com/docs/latest#special-jsx-attributes

**Comment by targetlucked69** [comment]
Yes I tried it, same error. The TypeScript error in vscode is gone, but still getting `Uncaught ReferenceError: dndzone is not defined`

**Comment by isaacHagoel** [comment]
can u send the exact config u've added?
i am no typescript guru but can have a look tomorrow

**Comment by targetlucked69** [comment]
ryan commented on my thread https://github.com/solidjs/solid/discussions/845#discussioncomment-2146959

**Comment by isaacHagoel** [comment]
Ah good to know. Were you able to use his advice to make it work?

**Comment by targetlucked69** [comment]
Yes. If using typescript, we can assign it to a local variable

```tsx
import { dndzone as dndZoneDirective } from "solid-dnd-directive";

const dndzone = dndZoneDirective
```
