### ISSUE TITLE
Is there a way to use a different element when dragging (rather than transforming)?

### ISSUE THREAD

**Issue by floer32** [isaacHagoel/solid-dnd-directive#7]
I'm having a little trouble using `transformDraggedElement` to get the effect I'm looking for. The DND elements I am using have a title and a body, and the body text can be long. When it's dragging, I'd like to show an element that has only the title, and not the body (or an abbreviated body). I've tried using `transformDraggedElement` and CSS but I haven't gotten the desired effect yet.

Is it possible to use a different element when dragging? (I checked the issues on `svelte-dnd-action` as well and I haven't found an example of this yet.)

----

Note: There's another DND library for Solid — that seems less feature-complete than `svelte-dnd-action`/`solid-dnd-directive` — but it implements a "drag overlay" feature ([code](https://github.com/thisbeyond/solid-dnd/blob/main/src/drag-overlay.tsx), [demo](https://solid-dnd.com/)), so it might offer useful example code of what I mean. I would offer to adapt it myself, but since it could involve both `svelte-dnd-action` and `solid-dnd-directive` the change might not be simple, so I figured I'd ask for your thoughts first.

**Comment by isaacHagoel** [comment]
One way of doing it would be this
https://svelte.dev/repl/2d3292db54bd445286731bde4a31f4d5?version=3.46.4

**Comment by floer32** [comment]
@isaacHagoel oh that makes perfect sense. Thank you! I'd tried using `#dnd-action-dragged-el`, but I hadn't used it together with `SHADOW_ITEM_MARKER_PROPERTY_NAME`. Together they're working like a charm. 

[Here's a fork of the `solid-dnd-directive` demo, with a similar change applied](https://codesandbox.io/s/fork-of-dnd-board-that-abbreviates-text-while-dragging-npjpuw?file=/src/App.jsx)

**Comment by isaacHagoel** [comment]
Cool. The reason SHADOW_ITEM_MARKER_PROPERTY_NAME is needed is because its
dimensions and other styles are applied to the dragged element in order to
show a preview of what it would look like when dropped. Another option is
to disable this morph behaviour altogether (the is an option you can pass
in)

**Comment by floer32** [comment]
Really appreciate your responses, you've made my day 😄
